# Generated by Django 2.0.2 on 2018-03-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40)),
                ('contact_number', models.CharField(max_length=20)),
                ('blood_types', models.CharField(max_length=15)),
            ],
        ),
    ]
