# Generated by Django 2.0.2 on 2018-04-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180403_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='contact_number',
            field=models.CharField(max_length=25),
        ),
    ]
