# Generated by Django 2.0.5 on 2018-05-20 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180403_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
