# Generated by Django 2.0.6 on 2018-08-18 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_info_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='blood_types',
            new_name='blood_group',
        ),
    ]
