# Generated by Django 2.0.6 on 2018-08-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180818_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='date_added',
        ),
        migrations.AddField(
            model_name='info',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='contact_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
