# Generated by Django 2.0.6 on 2018-08-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20180818_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=18, null=True),
        ),
    ]
