# Generated by Django 2.0.6 on 2018-08-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20180818_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='contact_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
